// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCheckboxGroup: typeof import('@nutui/nutui-taro')['CheckboxGroup']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutFormItemError: typeof import('@nutui/nutui-taro')['FormItemError']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
